# Generated by Django 5.2 on 2025-05-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0002_userreport_userreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
