# Generated by Django 5.2 on 2025-04-29 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0003_perfumeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfumeimage',
            name='perfume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='perfumes.perfume'),
        ),
    ]
