# Generated by Django 5.2 on 2025-05-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0007_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
