# Generated by Django 5.2 on 2025-05-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0009_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='category',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('unisex', 'Unisex')], default='unisex', max_length=10),
        ),
    ]
