# Generated by Django 5.2 on 2025-05-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0010_perfume_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
