# Generated by Django 5.2 on 2025-05-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0012_tradeoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeoffer',
            name='extra_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
