# Generated by Django 5.2 on 2025-05-14 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0013_tradeoffer_extra_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradeoffer',
            old_name='extra_payment',
            new_name='additional_payment',
        ),
        migrations.CreateModel(
            name='TradeDeliveryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('trade_offer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_info', to='perfumes.tradeoffer')),
            ],
        ),
    ]
