# Generated by Django 5.2 on 2025-05-14 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0014_rename_extra_payment_tradeoffer_additional_payment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradedeliveryinfo',
            name='trade_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_infos', to='perfumes.tradeoffer'),
        ),
        migrations.AlterUniqueTogether(
            name='tradedeliveryinfo',
            unique_together={('trade_offer', 'submitted_by')},
        ),
    ]
