# Generated by Django 5.2 on 2025-05-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0015_alter_tradedeliveryinfo_trade_offer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeoffer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('in_transit', 'In Transit'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
    ]
